# Generated by Django 4.1.7 on 2024-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
