# Generated by Django 4.1.7 on 2024-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0003_user_delete_alloweduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
