# Generated by Django 4.1.7 on 2024-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
