# Generated by Django 4.1.7 on 2024-08-06 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0006_user_cups_user_first_name_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cups_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_cup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
