# Generated by Django 4.1.7 on 2024-08-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0007_user_cups_today_user_last_cup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
