# Generated by Django 4.1.7 on 2024-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0009_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
