# Generated by Django 4.1.7 on 2024-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0010_user_amount_due_user_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
