# Generated by Django 4.1.7 on 2024-08-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0011_alter_user_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_due2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='cups2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
