# Generated by Django 4.1.7 on 2024-08-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0012_user_amount_due2_user_cups2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='amount_due2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cups2',
        ),
    ]
