# Generated by Django 4.1.7 on 2024-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0013_remove_user_amount_due2_remove_user_cups2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historical_amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
