# Generated by Django 4.1.7 on 2024-12-20 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappcoffee', '0014_user_historical_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cups_new',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='historical_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
